spring:
  application:
    name: infra-config-server
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/hkliya/spring-cloud-config-server
server:
  port: 8082